/* 6) Crear un procedimiento igual que el anterior, pero que muestre también las personas que trabajan en el departamento, 
pasando el parámetro nombre.*/

Use clinica

go

CREATE PROCEDURE PERSONASDEPT 
@DEPT NVARCHAR (30)
AS
SELECT E.DEPT_NO AS [NUMERO DEPT], D.DNOMBRE AS [NOMBRE], COUNT(*) AS [NUMERO EMPLEADOS]
FROM EMP AS E
INNER JOIN DEPT AS D ON E.DEPT_NO = D.DEPT_NO
WHERE D.DNOMBRE = @DEPT
GROUP BY D.DNOMBRE, E.DEPT_NO
SELECT E.DEPT_NO AS [N° DEPARTAMENTO], D.DNOMBRE AS [DEPARTAMENTO], E.APELLIDO, E.SALARIO
FROM EMP AS E
INNER JOIN DEPT AS D ON E.DEPT_NO = D.DEPT_NO
WHERE D.DNOMBRE = @DEPT

EXEC PERSONASDEPT 'CONTABILIDAD'

