/* 5) Hacer un procedimiento que pueda ingresar un nuevo empleado.*/

Use clinica

go

CREATE PROCEDURE INSERTA_EMPLEADO
@EMP_NO INT,
@APELLIDO NVARCHAR (20),
@OFICIO NVARCHAR (20),
@DIR INT,
@FECHA_ALT SMALLDATETIME,
@SALARIO INT,
@COMISION INT,
@DEPT_NO INT
AS
INSERT INTO EMP VALUES
(@EMP_NO,
@APELLIDO,
@OFICIO,
@DIR,
@FECHA_ALT,
@SALARIO,
@COMISION,
@DEPT_NO)

EXEC INSERTA_EMPLEADO 7895,'SUAREZ','EMPLEADO',0,'2015-05-26',16000,0,20

